### ISSUE TITLE
Supernova completion

### ISSUE THREAD

**Issue by huitseeker** [lurk-lab/arecibo#90]
This tracks the supplementary work we want to accomplish with SuperNova before we upstream it in a PR to Microsoft/Nova:

- [x] #94 
- [x] #53 
- [ ] rationalize the circuit index passing (#64 #175)
- [x] Make clear iter_base_step is just a constructor (#63)
- [x] transform the NIVC examples into tests (see also #52, closed by #92)
- [ ] ~finish the CompressedSNARK V0 implementation (#80)~
- [x] finish the CompressedSNARK V1 implementation  << (@mpenciak / @adr1anh to flesh out what that V1 looks like)
- [x] #93
